# Generated by Django 5.2.3 on 2025-06-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productattribute_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PT', 'Pant'), ('ST', 'Shirt'), ('VT', 'Vest'), ('SW', 'Sweater'), ('CT', 'Coat & Blazer')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price without variations', max_digits=10),
        ),
    ]
