# Generated by Django 5.2.3 on 2025-06-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_category_alter_product_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Pant', 'Pant'), ('Shirt', 'Shirt'), ('T-Shirt', 'T-Shirt'), ('Sweater', 'Sweater'), ('Formal', 'Coat & Blazer')], default='', max_length=50),
        ),
    ]
